{"ast":null,"code":"/** PURE_IMPORTS_START tslib,_innerSubscribe PURE_IMPORTS_END */\nimport * as tslib_1 from \"tslib\";\nimport { SimpleOuterSubscriber, SimpleInnerSubscriber, innerSubscribe } from '../innerSubscribe';\nexport function catchError(selector) {\n  return function catchErrorOperatorFunction(source) {\n    var operator = new CatchOperator(selector);\n    var caught = source.lift(operator);\n    return operator.caught = caught;\n  };\n}\n\nvar CatchOperator = /*@__PURE__*/function () {\n  function CatchOperator(selector) {\n    this.selector = selector;\n  }\n\n  CatchOperator.prototype.call = function (subscriber, source) {\n    return source.subscribe(new CatchSubscriber(subscriber, this.selector, this.caught));\n  };\n\n  return CatchOperator;\n}();\n\nvar CatchSubscriber = /*@__PURE__*/function (_super) {\n  tslib_1.__extends(CatchSubscriber, _super);\n\n  function CatchSubscriber(destination, selector, caught) {\n    var _this = _super.call(this, destination) || this;\n\n    _this.selector = selector;\n    _this.caught = caught;\n    return _this;\n  }\n\n  CatchSubscriber.prototype.error = function (err) {\n    if (!this.isStopped) {\n      var result = void 0;\n\n      try {\n        result = this.selector(err, this.caught);\n      } catch (err2) {\n        _super.prototype.error.call(this, err2);\n\n        return;\n      }\n\n      this._unsubscribeAndRecycle();\n\n      var innerSubscriber = new SimpleInnerSubscriber(this);\n      this.add(innerSubscriber);\n      var innerSubscription = innerSubscribe(result, innerSubscriber);\n\n      if (innerSubscription !== innerSubscriber) {\n        this.add(innerSubscription);\n      }\n    }\n  };\n\n  return CatchSubscriber;\n}(SimpleOuterSubscriber);","map":{"version":3,"mappings":";AAKA,OAAO,KAAEA,OAAT,MAAS,OAAT;AAkFA,SAAMC,qBAAN,EACEC,qBADF,EACkDC,cADlD,QACkD,mBADlD;OAGE,SAAOC,UAAP,CAAgBC,QAAhB,EAAgB;SACd,SAAcC,0BAAd,CAAmCC,MAAnC,EAA6C;IAC7C,IAAMC,QAAM,GAAG,IAAMC,aAAN,CAAoBJ,QAApB,CAAf;IACA,UAAQ,SAAS,KAAT,CAAeG,QAAf,CAAR;IACA;EACH;AAED;;IAGEC,6BAAyF;WAArEA,wBAAqE;IACxF;EAED;;eACS,WAAOC,OAAU,UAAIC,UAAJ,EAAoBJ,MAApB,EAAgC;IACzD;EACH;;EATA,OASCE,aATD;AAgBA,CAb2F;;IAavDG,yCAA+BC,MAA/B,EAA+B;EACjEb,mCAAYa,MAAZ;;WAAAD,gBAGEE,aAAMT,UAAYU,QACnB;IAHmB,8BAAqED,WAArE,KAAqE,IAArE;;IACAE;;IAEnB;EAOD;;iBACY,WAAWC;QACnB,MAAIC,WAAM;MACV,IAAIC,eAAJ;;UACE;QACDA;MAAC,SACAC;QACAP,OAAOQ,SAAP,CAAOJ,KAAP,CAAOP,IAAP,CAAO,IAAP,EAAOU,IAAP;;QACD;MACD;;MACA,KAAME,sBAAN;;MACA,IAAIC,eAAK,OAAiBrB,qBAAjB,CAAiB,IAAjB,CAAT;MACA,KAAMsB,GAAN,CAAMD,eAAN;MAIA,IAAIE,iBAAiB,iBAAK,SAAiBF,eAAjB,CAA1B;;UACEE,iBAAS,sBAAmB;QAC7B;MACF;IACF;EACH;;EAjCoC;CAAA","names":["tslib_1","SimpleOuterSubscriber","SimpleInnerSubscriber","innerSubscribe","catchError","selector","catchErrorOperatorFunction","source","operator","CatchOperator","call","subscriber","CatchSubscriber","_super","destination","caught","_this","error","isStopped","result","err2","prototype","_unsubscribeAndRecycle","innerSubscriber","add","innerSubscription"],"sources":["/home/rybakisa/Desktop/TEMP/HackaTON/TON Ads/ton-ads/node_modules/rxjs/src/internal/operators/catchError.ts"],"sourcesContent":["import { Operator } from '../Operator';\nimport { Subscriber } from '../Subscriber';\nimport { Observable } from '../Observable';\n\nimport { ObservableInput, OperatorFunction, ObservedValueOf } from '../types';\nimport { SimpleOuterSubscriber, SimpleInnerSubscriber, innerSubscribe } from '../innerSubscribe';\n\n/* tslint:disable:max-line-length */\nexport function catchError<T, O extends ObservableInput<any>>(selector: (err: any, caught: Observable<T>) => O): OperatorFunction<T, T | ObservedValueOf<O>>;\n/* tslint:enable:max-line-length */\n\n/**\n * Catches errors on the observable to be handled by returning a new observable or throwing an error.\n *\n * ![](catch.png)\n *\n * ## Examples\n * Continues with a different Observable when there's an error\n *\n * ```ts\n * import { of } from 'rxjs';\n * import { map, catchError } from 'rxjs/operators';\n *\n * of(1, 2, 3, 4, 5).pipe(\n *     map(n => {\n *   \t   if (n === 4) {\n * \t       throw 'four!';\n *       }\n *\t     return n;\n *     }),\n *     catchError(err => of('I', 'II', 'III', 'IV', 'V')),\n *   )\n *   .subscribe(x => console.log(x));\n *   // 1, 2, 3, I, II, III, IV, V\n * ```\n *\n * Retries the caught source Observable again in case of error, similar to retry() operator\n *\n * ```ts\n * import { of } from 'rxjs';\n * import { map, catchError, take } from 'rxjs/operators';\n *\n * of(1, 2, 3, 4, 5).pipe(\n *     map(n => {\n *   \t   if (n === 4) {\n *   \t     throw 'four!';\n *       }\n * \t     return n;\n *     }),\n *     catchError((err, caught) => caught),\n *     take(30),\n *   )\n *   .subscribe(x => console.log(x));\n *   // 1, 2, 3, 1, 2, 3, ...\n * ```\n *\n * Throws a new error when the source Observable throws an error\n *\n * ```ts\n * import { of } from 'rxjs';\n * import { map, catchError } from 'rxjs/operators';\n *\n * of(1, 2, 3, 4, 5).pipe(\n *     map(n => {\n *       if (n === 4) {\n *         throw 'four!';\n *       }\n *       return n;\n *     }),\n *     catchError(err => {\n *       throw 'error in source. Details: ' + err;\n *     }),\n *   )\n *   .subscribe(\n *     x => console.log(x),\n *     err => console.log(err)\n *   );\n *   // 1, 2, 3, error in source. Details: four!\n * ```\n *\n *  @param {function} selector a function that takes as arguments `err`, which is the error, and `caught`, which\n *  is the source observable, in case you'd like to \"retry\" that observable by returning it again. Whatever observable\n *  is returned by the `selector` will be used to continue the observable chain.\n * @return {Observable} An observable that originates from either the source or the observable returned by the\n *  catch `selector` function.\n * @name catchError\n */\nexport function catchError<T, O extends ObservableInput<any>>(\n  selector: (err: any, caught: Observable<T>) => O\n): OperatorFunction<T, T | ObservedValueOf<O>> {\n  return function catchErrorOperatorFunction(source: Observable<T>): Observable<T | ObservedValueOf<O>> {\n    const operator = new CatchOperator(selector);\n    const caught = source.lift(operator);\n    return (operator.caught = caught as Observable<T>);\n  };\n}\n\nclass CatchOperator<T, R> implements Operator<T, T | R> {\n  caught: Observable<T>;\n\n  constructor(private selector: (err: any, caught: Observable<T>) => ObservableInput<T | R>) {\n  }\n\n  call(subscriber: Subscriber<R>, source: any): any {\n    return source.subscribe(new CatchSubscriber(subscriber, this.selector, this.caught));\n  }\n}\n\n/**\n * We need this JSDoc comment for affecting ESDoc.\n * @ignore\n * @extends {Ignored}\n */\nclass CatchSubscriber<T, R> extends SimpleOuterSubscriber<T, T | R> {\n  constructor(destination: Subscriber<any>,\n              private selector: (err: any, caught: Observable<T>) => ObservableInput<T | R>,\n              private caught: Observable<T>) {\n    super(destination);\n  }\n\n  // NOTE: overriding `error` instead of `_error` because we don't want\n  // to have this flag this subscriber as `isStopped`. We can mimic the\n  // behavior of the RetrySubscriber (from the `retry` operator), where\n  // we unsubscribe from our source chain, reset our Subscriber flags,\n  // then subscribe to the selector result.\n  error(err: any) {\n    if (!this.isStopped) {\n      let result: any;\n      try {\n        result = this.selector(err, this.caught);\n      } catch (err2) {\n        super.error(err2);\n        return;\n      }\n      this._unsubscribeAndRecycle();\n      const innerSubscriber = new SimpleInnerSubscriber(this);\n      this.add(innerSubscriber);\n      const innerSubscription = innerSubscribe(result, innerSubscriber);\n      // The returned subscription will usually be the subscriber that was\n      // passed. However, interop subscribers will be wrapped and for\n      // unsubscriptions to chain correctly, the wrapper needs to be added, too.\n      if (innerSubscription !== innerSubscriber) {\n        this.add(innerSubscription);\n      }\n    }\n  }\n}\n"]},"metadata":{},"sourceType":"module"}